export const CHANGE_ACTIVE_SCREEN = 'CHANGE_ACTIVE_SCREEN'

export const TASKS_GROUP_NEW_OPEN = 'TASKS_GROUP_NEW_OPEN'

export const TASKS_GROUP_NEW_CLOSE = 'TASKS_GROUP_NEW_CLOSE'

export const TASKS_GROUP_NEW_CLEAR = 'TASKS_GROUP_NEW_CLEAR'

export const TASKS_GROUP_NEW_SET = 'TASKS_GROUP_NEW_SET'

export const TASKS_GROUP_EDIT_OPEN = 'TASKS_GROUP_EDIT_OPEN'

export const TASKS_GROUP_EDIT_CLOSE = 'TASKS_GROUP_EDIT_CLOSE'

export const TASKS_GROUP_EDIT_SET = 'TASKS_GROUP_EDIT_SET'

export const TASKS_GROUP_SET_ACTIVE = 'TASKS_GROUP_SET_ACTIVE'

export const TASKS_NEW_GROUP = 'TASKS_NEW_GROUP'

export const TASKS_UPDATE_GROUP = 'TASKS_UPDATE_GROUP'

export const TASKS_DELETE_GROUP = 'TASKS_DELETE_GROUP'

export const TASKS_NEW_TASKS = 'TASKS_NEW_TASKS'

export const TASKS_UPDATE_TASKS = 'TASKS_UPDATE_TASKS'

export const TASKS_DELETE_TASK = 'TASKS_DELETE_TASK'

export const TASKS_CLEAR = 'TASKS_CLEAR'

export const TASKS_GROUP_DELETE_OPEN = 'TASKS_GROUP_DELETE_OPEN'

export const TASKS_GROUP_DELETE_CLOSE = 'TASKS_GROUP_DELETE_CLOSE'

export const TASKS_CREATE_OPEN = 'TASKS_CREATE_OPEN'

export const TASKS_CREATE_CLOSE = 'TASKS_CREATE_CLOSE'

export const TASKS_CREATE_SET = 'TASKS_CREATE_SET'

export const TASKS_STATUS_UPDATE = 'TASKS_STATUS_UPDATE'

export const TASKS_CHECK = 'TASKS_CHECK'

export const BILLING_PROFILES_UPDATE = 'BILLING_PROFILES_UPDATE'

export const BILLING_PROFILE_OPEN = 'BILLING_PROFILE_OPEN'

export const BILLING_PROFILE_CLOSE = 'BILLING_PROFILE_CLOSE'

export const BILLING_SET_PROFILE = 'BILLING_SET_PROFILE'

export const BILLING_CLEAR_PROFILE = 'BILLING_CLEAR_PROFILE'

export const BILLING_NEW_PROFILE = 'BILLING_NEW_PROFILE'

export const BILLING_DELETE_PROFILE = 'BILLING_DELETE_PROFILE'

export const BILLING_UPDATE_PROFILE = 'BILLING_UPDATE_PROFILE'

export const PROXIES_GROUP_SET_ACTIVE = 'PROXIES_GROUP_ACTIVE'

export const PROXIES_GROUP_CREATE_OPEN = 'PROXIES_GROUP_CREATE_OPEN'

export const PROXIES_GROUP_CREATE_CLOSE = 'PROXIES_GROUP_CREATE_CLOSE'

export const PROXIES_GROUP_DELETE_OPEN = 'PROXIES_GROUP_DELETE_OPEN'

export const PROXIES_GROUP_DELETE_CLOSE = 'PROXIES_GROUP_DELETE_CLOSE'

export const PROXIES_ADD_OPEN = 'PROXIES_GROUP_ADD_OPEN'

export const PROXIES_ADD_CLOSE = 'PROXIES_GROUP_ADD_CLOSE'

export const PROXIES_NEW_GROUP = 'PROXIES_NEW_GROUP'

export const PROXIES_DELETE_GROUP = 'PROXIES_DELETE_GROUP'

export const PROXIES_CLEAR_GROUP = 'PROXIES_CLEAR_GROUP'

export const PROXIES_ADD_PROXIES = 'PROXIES_ADD_PROXIES'

export const PROXIES_DELETE_PROXIES = 'PROXIES_DELETE_PROXIES'

export const PROXIES_TEST_UPDATE = 'PROXIES_TEST_UPDATE'

export const PROXIES_TEST = 'PROXIES_TEST'

export const ACCOUNTS_GROUP_SET_ACTIVE = 'ACCOUNTS_GROUP_SET_ACTIVE'

export const ACCOUNTS_GROUP_CREATE_OPEN = 'ACCOUNTS_GROUP_CREATE_OPEN'

export const ACCOUNTS_GROUP_CREATE_CLOSE = 'ACCOUNTS_GROUP_CREATE_CLOSE'

export const ACCOUNTS_GROUP_DELETE_OPEN = 'ACCOUNTS_GROUP_DELETE_OPEN'

export const ACCOUNTS_GROUP_DELETE_CLOSE = 'ACCOUNTS_GROUP_DELETE_CLOSE'

export const ACCOUNTS_ADD_OPEN = 'ACCOUNTS_ADD_OPEN'

export const ACCOUNTS_ADD_CLOSE = 'ACCOUNTS_ADD_CLOSE'

export const ACCOUNTS_UPDATE_STATE = 'ACCOUNTS_UPDATE_STATE'

export const ACCOUNTS_NEW_GROUP = 'ACCOUNTS_NEW_GROUPS'

export const ACCOUNTS_DELETE_GROUP = 'ACCOUNTS_DELETE_GROUP'

export const ACCOUNTS_ADD_ACCOUNTS = 'ACCOUNTS_ADD_ACCOUNTS'

export const ACCOUNTS_DELETE_ACCOUNTS = 'ACCOUNTS_DELETE_ACCOUNTS'

export const SHIPPING_RATES_GROUP_CREATE_OPEN = 'SHIPPING_RATES_GROUP_CREATE_OPEN'

export const SHIPPING_RATES_GROUP_CREATE_CLOSE = 'SHIPPING_RATES_GROUP_CREATE_CLOSE'

export const SHIPPING_RATES_ADD_OPEN = 'SHIPPING_RATES_ADD_OPEN'

export const SHIPPING_RATES_ADD_CLOSE = 'SHIPPING_RATES_ADD_CLOSE'

export const SHIPPING_RATES_UPDATE_STATE = 'SHIPPING_RATES_UPDATE_STATE'

export const SETTINGS_WEBHOOK_UPDATE = 'SETTINGS_WEBHOOK_UPDATE'

export const SETTINGS_TWOCAPTCHA_UPDATE = 'SETTINGS_TWOCAPTCHA_UPDATE'

export const SETTINGS_CAPMONSTER_UPDATE = 'SETTINGS_CAPMONSTER_UPDATE'

export const SETTINGS_TWOCAPTCHA_STATUS_UPDATE = 'SETTINGS_TWOCAPTCHA_STATUS_UPDATE'

export const SETTINGS_CAPMONSTER_STATUS_UPDATE = 'SETTINGS_CAPMONSTER_STATUS_UPDATE'

export const GROUPS_CLEAR = 'GROUPS_CLEAR'