name: release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and publish CapsuleAIO
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.17.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create Build
        run: |
          npm ci
          npm run build
          npm run dist
      - name: Upload Release Asset
        uses: alexellis/upload-assets@0.2.2          # ✨✨✨
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./bin/*.msi"]'
